uml_mconsole SURABAYA halt
uml_mconsole PASURUAN halt
uml_mconsole PROBOLINGGO halt
uml_mconsole BATU halt
uml_mconsole MADIUN halt
uml_mconsole KEDIRI halt
uml_mconsole BLITAR halt
uml_mconsole MALANG halt
uml_mconsole MOJOKERTO halt
uml_mconsole SAMPANG halt
uml_mconsole BONDOWOSO halt
uml_mconsole JEMBER halt
uml_mconsole BANYUWANGI halt
uml_mconsole SIDOARJO halt
uml_mconsole JOMBANG halt
uml_mconsole BOJONEGORO halt
uml_mconsole NGANJUK halt
uml_mconsole LUMAJANG halt
uml_mconsole TULUNGAGUNG halt